### ISSUE TITLE
UnboundLocalError: local variable 'bootset' referenced before assignment ```

### ISSUE THREAD

**Issue by terrycojones** [PoonLab/OpenRDP#105]
I just ran into this:

```
Traceback (most recent call last):
  File "/Users/terry/miniconda3/envs/310/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/terry/miniconda3/envs/310/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/Users/terry/miniconda3/envs/310/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/Users/terry/dark-matter/hbv/recombination/paper-dieter/openrdp/process.py", line 15, in runMethod
    return scanner.run_scans(fasta).dict[method]
  File "/Users/terry/.local/lib/python3.10/site-packages/openrdp/__init__.py", line 300, in run_scans
    if bootset:
UnboundLocalError: local variable 'bootset' referenced before assignment
```

The line `if alias in 'bootscan':` is incorrect, it should be something like `if alias == 'bootscan':` (or `if alias in ('bootscan',):` etc).

But in any case, it looks like `bootset` is never set unless `bootscan` is given as one of the methods.

**Comment by WilliamZekaiWang** [comment]
Oh sorry about this one, I found this issue a week back and forgot to log it. 

The fix is pushed to the `dev` branch and not the `master` branch yet

**Comment by terrycojones** [comment]
https://github.com/PoonLab/OpenRDP/blob/dev/openrdp/__init__.py#L235 on the `dev` branch still has `if alias in 'bootscan':` and it's also on line 389 in the same file.
