### ISSUE TITLE
Typo in default config

### ISSUE THREAD

**Issue by sejmodha** [PoonLab/OpenRDP#33]
Hi There,

I got the following error when running the OpenRDP pipeline which is due to a minor typo in the default config file.
The script fails as it is looking for the key `Siscan` but the [default_config.ini](https://github.com/PoonLab/OpenRDP/blob/master/openrdp/scripts/default_config.ini) has parameters specified under `[SisScan]` in line 72.

```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(__main__.py:31383): Gdk-CRITICAL **: 14:36:25.273: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Starting 3Seq Analysis
Finished 3Seq Analysis
Starting GENECONV Analysis
Finished GENECONV Analysis
Setting Up MaxChi Analysis
Setting Up Chimaera Analysis
Setting Up RDP Analysis
Setting Up Bootscan Analysis
Starting Scanning Phase of Bootscan/Recscan
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'Siscan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/OpenRDP-0.0.1-py3.6.egg/openrdp/__main__.py", line 4, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/OpenRDP-0.0.1-py3.6.egg/openrdp/main.py", line 174, in main
    run_siscan, run_maxchi, run_chimaera, run_bootscan, args.quiet)
  File "/usr/local/lib/python3.6/dist-packages/OpenRDP-0.0.1-py3.6.egg/openrdp/main.py", line 146, in openrdp
    scanner.run_scans(aln)
  File "/usr/local/lib/python3.6/dist-packages/OpenRDP-0.0.1-py3.6.egg/openrdp/scripts/run_scans.py", line 125, in run_scans
    siscan = Siscan(alignment, settings=dict(config.items('Siscan')))
  File "/usr/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'Siscan'
Finished Scanning Phase of Bootscan/Recscan
Setting Up Siscan Analysis
```

**Comment by ArtPoon** [comment]
D'oh!  Thanks for the bug report and proposed fix!

**Comment by ArtPoon** [comment]
Made quick edit to `default_config.ini`, need to test before closing issue
