### ISSUE TITLE
UnboundLocalError in both master and dev branch

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/OpenRDP#58]
commit 333eba7586d4ee1aa4011a7e84e56da12d4e15b7
```console
(venv) art@Wernstrom OpenRDP % openrdp -c tests/test_cfg.ini tests/test_neisseria.fasta
Loading configuration from tests/test_cfg.ini
Starting 3Seq Analysis
Finished 3Seq Analysis
Starting GENECONV Analysis
Finished GENECONV Analysis
Setting up bootscan analysis...
Starting Scanning Phase of Bootscan/Recscan
Finished Scanning Phase of Bootscan/Recscan
Setting up maxchi analysis...
Setting up siscan analysis...
Setting up chimaera analysis...
Setting up rdp analysis...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/art/git/OpenRDP/venv/lib/python3.10/site-packages/OpenRDP-0.1.0-py3.10.egg/openrdp/bootscan.py", line 176, in execute
    print("Scanning triplet {} / {}".format(i, self.total_triplet_combinations))
UnboundLocalError: local variable 'i' referenced before assignment
"""
```

**Comment by ArtPoon** [comment]
```console
(venv) art@Wernstrom OpenRDP % openrdp -c tests/test_cfg.ini tests/test_neisseria.fasta
Loading configuration from tests/test_cfg.ini
Starting 3Seq Analysis
Finished 3Seq Analysis
Starting GENECONV Analysis
Finished GENECONV Analysis
Setting up bootscan analysis...
Starting Scanning Phase of Bootscan/Recscan
Finished Scanning Phase of Bootscan/Recscan
Setting up maxchi analysis...
Setting up siscan analysis...
Setting up chimaera analysis...
Setting up rdp analysis...
Scanning triplet 0 / 4.0
Scanning triplet 0 / 4.0
Scanning triplet 1 / 4.0
Scanning triplet 2 / 4.0
Scanning triplet 3 / 4.0
Scanning triplet 1 / 4.0
Scanning triplet 0 / 4.0
Scanning triplet 1 / 4.0
Scanning triplet 2 / 4.0
Scanning triplet 3 / 4.0
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/art/git/OpenRDP/venv/lib/python3.10/site-packages/OpenRDP-0.1.0-py3.10.egg/openrdp/bootscan.py", line 184, in execute
    f = h5py.File(self.dt_matrix_file, 'r')
  File "/Users/art/git/OpenRDP/venv/lib/python3.10/site-packages/h5py-3.8.0-py3.10-macosx-12-x86_64.egg/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/Users/art/git/OpenRDP/venv/lib/python3.10/site-packages/h5py-3.8.0-py3.10-macosx-12-x86_64.egg/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/var/folders/56/3y9v479n0g55nm_b_51dvv_m0000gn/T/dt_mtrx_f3z6ebep', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
"""
```

**Comment by ArtPoon** [comment]
All unit tests pass - we need more tests:
```console
(venv) art@Wernstrom OpenRDP % python3 -m unittest
...........................................Error: <_io.StringIO object at 0x100acc550> does not appear to contain a valid alignment!
.Alignment contains invalid characters XZ.
Sequences can only contain A,T,G,C,-,N.
..............
----------------------------------------------------------------------
Ran 58 tests in 34.043s

OK
```
