### ISSUE TITLE
3Seq method not running on windows 11

### ISSUE THREAD

**Issue by SandeepThokala** [PoonLab/OpenRDP#65]
Error message:
```
Starting 3Seq Analysis
  ERROR: Loading fail! The P-value table file may be corrupt.

Traceback (most recent call last):
  File ".\OpenRDP\bin\openrdp", line 44, in <module>
    results = scanner.run_scans(args.infile, args.ref)
  File "site-packages\openrdp-0.1.0-py3.10.egg\openrdp\__init__.py", line 219, in run_scans
    results.dict['threeseq'] = three_seq.execute()
  File "site-packages\openrdp-0.1.0-py3.10.egg\openrdp\threeseq.py", line 51, in execute
    ts_results = self.parse_output(out_path)
  File "site-packages\openrdp-0.1.0-py3.10.egg\openrdp\threeseq.py", line 65, in parse_output
    with open(out_path) as out_handle:
FileNotFoundError: [Errno 2] No such file or directory: 'AppData\\Local\\Temp\\tmpieigj94b.3s.rec.csv'
```
`.3s.rec` temp files are not being created

**Comment by SandeepThokala** [comment]
3Seq method is working without any issue in `Jesry`

**Comment by ArtPoon** [comment]
Seems like the binary is not compatible with Windows 11 then?  I guess we will have to update the README to indicate that newer versions of Windows are not currently supported, and close for now.

**Comment by ArtPoon** [comment]
@SandeepThokala please update readme and close, thanks!
