### ISSUE TITLE
Unit test failures

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/OpenRDP#80]
Using macOS 14.3.1 and Python 3.11.5 on commit faae2dcfb2893bf85605c21fe35d42627758e8a2

```python
======================================================================
ERROR: test_parse_results_crf (tests.test_three_seq.Test3Seq.test_parse_results_crf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/art/git/OpenRDP/tests/test_three_seq.py", line 21, in test_parse_results_crf
    result = self.crf_test.execute()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/art/git/OpenRDP/openrdp/threeseq.py", line 54, in execute
    ts_results = self.parse_output(out_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/art/git/OpenRDP/openrdp/threeseq.py", line 68, in parse_output
    with open(out_path) as out_handle:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/56/3y9v479n0g55nm_b_51dvv_m0000gn/T/tmpv8h0naye.3s.rec'

======================================================================
ERROR: test_parse_results_long (tests.test_three_seq.Test3Seq.test_parse_results_long)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/art/git/OpenRDP/tests/test_three_seq.py", line 15, in test_parse_results_long
    result = self.long_test.execute()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/art/git/OpenRDP/openrdp/threeseq.py", line 54, in execute
    ts_results = self.parse_output(out_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/art/git/OpenRDP/openrdp/threeseq.py", line 68, in parse_output
    with open(out_path) as out_handle:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/56/3y9v479n0g55nm_b_51dvv_m0000gn/T/tmpnjujso1x.3s.rec'
```
These are probably related to issue #76

**Comment by ArtPoon** [comment]
Dumb mistake in my debugging branch, fixed and closing
